sort: quicksort.h quicksort_run.c quicksort.c quicksort_median.c quicksort_hybrid.c quicksort_helper.c
	gcc quicksort_run.c quicksort.c quicksort_median.c quicksort_hybrid.c quicksort_helper.c -o sort -lm
